trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  GIT_AUTHOR_NAME: 'Azure DevOps Pipeline'
  GIT_AUTHOR_EMAIL: 'workwithme@saiobili.com'
  GITHUB_REPO: 'sairamobili/iac_works'

steps:
  - checkout: self
    persistCredentials: true
    clean: true
    fetchDepth: 0

  - task: InstallSSHKey@0
    displayName: 'Install SSH key for GitHub push'
    inputs:
      sshPublicKey: ''
      sshKeySecureFile: 'myado'
      knownHostsEntry: 'github.com'

  - script: |
      echo "Verifying local Git state..."
      git branch -a
      git status
      git log --oneline -5
    displayName: 'Debug: Show Git branch and history'

  - script: |
      git config --global user.name "$GIT_AUTHOR_NAME"
      git config --global user.email "$GIT_AUTHOR_EMAIL"
      git remote add github git@github.com:$GITHUB_REPO.git
      git push --force github HEAD:refs/heads/main
    displayName: 'Push main → main on GitHub'

  - script: |
      echo "##[section]Changes in this commit were pushed from Azure Repos via Azure Pipeline."
    displayName: 'Annotate commit source'

  # SSH key cleanup is handled automatically by InstallSSHKey@0